services:
  db:
    image: postgres@sha256:3e43515057e113ee741fca2f621f15300be34a6d4a8dfcf2e20651288c8272f3
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  init-db:
    image: ${INIT_DB_IMAGE:-llm-api-gateway-init-db:latest}
    build:
      context: ./
      dockerfile: postgreSQL/Dockerfile
    environment:
      RESET_DB: "false"
      CREATE_MOCK_DATA: "false"
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "until pg_isready -h db -U $POSTGRES_USER; do sleep 1; done;
              if [ \"$$RESET_DB\" = 'true' ]; then
                python tools/db-bootstrap.py --reset;
              else
                python tools/db-bootstrap.py;
              fi;
              
              if [ \"$$CREATE_MOCK_DATA\" = 'true' ]; then
                python tools/create_mock_data.py
              fi;
              python tools/check_tables.py"
    restart: "no"

  gateway:
    image: ${GATEWAY_IMAGE:-llm-api-gateway:latest}
    build:
      context: ./
      dockerfile: gateway/Dockerfile
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
    depends_on:
      - db
    ports:
      - "8000:8000"

  dashboard-backend:
    image: ${DASHBOARD_BACKEND_IMAGE:-llm-api-gateway-dashboard-backend:latest}
    build:
      context: ./
      dockerfile: dashboard/backend/Dockerfile
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
    depends_on:
      - db
    ports:
      - "8080:8080"

  dashboard-frontend:
    image: ${DASHBOARD_FRONTEND_IMAGE:-llm-api-gateway-dashboard-frontend:latest}
    build:
      context: ./
      dockerfile: dashboard/frontend/Dockerfile
      args:
        FRONTEND_ADDRESS: ${FRONTEND_ADDRESS:-http://localhost}
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173 || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 10
    depends_on:
      - dashboard-backend
    ports:
      - "5173:5173"

volumes:
  pg_data:
